apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: app1-test
        url: http://localhostapp1
      - cluster: app2
        url: http://localhostapp2
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/Sanjivbv-Adappt/argo-cd-app-templates.git
        targetRevision: HEAD
        path: applications/{{cluster}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
