apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: app1
        url: https://1.2.3.4
      - cluster: app2
        url: https://2.4.6.8
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: git@github.com:Sanjivbv-Adappt/argo-cd-app-templates.git
        targetRevision: HEAD
        path: applications/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd
