apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - cluster: {}
  template:
    sourceType: directory
    directory:
      recurse: true
      jsonnet: {}
      sourcePath: /argocd  # Assuming app-set.yaml is in the argocd directory
