apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - clusterSelector:
        matchLabels:
          name: my-app
      namespaceSelector:
        matchLabels:
          name: namespace
        generate: expression
        expression: "'namespace-' + cluster.metadata.name"
  template:
    sourceType: directory
    directory:
      recurse: true
      jsonnet: {}
      sourcePath: /applications
