apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - cluster:
        name: my-app
  template:
    sourceType: directory
    directory:
      recurse: true
      jsonnet: {}
      sourcePath: /applications
