apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - cluster:
        name: my-app
        clusterParams:
          - name: namespace
            generate: expression
            expression: "'namespace-' + cluster.metadata.name"
  template:
    sourceType: directory
    directory:
      recurse: true
      jsonnet: {}
