apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - cluster: {}
  template:
    spec:
      project: default
      source:
        repoURL: https://github.com/Sanjivbv-Adappt/argo-cd-app-templates.git
        targetRevision: HEAD
        path: applications
