apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - cluster: {}
  template:
    sourceType: directory
    directory: /applications
      recurse: true
      jsonnet: {}
